#!/bin/bash
#SBATCH --output="/storage/research/igmp_dp_workspace/garciabaroja_javier/PW_reports/database/pathodb/logs/pathodb_setup_%j.out"


# =============================================================================
# PathoDB — PostgreSQL setup for HPC (no Docker, no root)
# Run this ONCE interactively (not as a SLURM job) to initialise the database.
#
# Usage:
#   bash setup_postgres_hpc.sh
#
# Requirements:
#   module load PostgreSQL   (or whichever module name your cluster uses)
# =============================================================================

set -euo pipefail

# ── PostgreSQL binary path (from: module show PostgreSQL) ─────────────────────
PG_BIN="/software.9/software/PostgreSQL/16.4-GCCcore-13.3.0/bin"
export PATH="$PG_BIN:$PATH"

# ── Configuration — edit these paths to match your storage ────────────────────
# Use a high-capacity research storage path, not your home directory
PGDATA="/storage/research/igmp_dp_workspace/garciabaroja_javier/PW_reports/database/pathodb/pgdata"

PGPORT=15432          # Use a non-standard port to avoid conflicts with system PG
PGDB="pathodb"
PGUSER="jgbaroja"
SCHEMA="/storage/research/igmp_dp_workspace/garciabaroja_javier/PW_reports/database/pathodb/db/schema.sql"
ENV_FILE="$(dirname "$0")/.env"

# ─────────────────────────────────────────────────────────────────────────────
echo "=== PathoDB PostgreSQL Setup ==="
echo "Data directory : $PGDATA"
echo "Port           : $PGPORT"
echo "Database       : $PGDB"
echo "User           : $PGUSER"

# 1. Initialise database cluster (only needed once)
if [ -d "$PGDATA" ]; then
    echo "[SKIP] Data directory already exists — skipping initdb"
else
    echo "[1/5] Initialising PostgreSQL cluster..."
    initdb -D "$PGDATA" --encoding=UTF8 --locale=en_US.UTF-8
    echo "      Done."
fi

# 2. Configure PostgreSQL to listen on custom port
echo "[2/5] Configuring PostgreSQL..."
cat >> "$PGDATA/postgresql.conf" << EOF

# PathoDB custom settings
port = $PGPORT
log_directory = '$PGDATA/logs'
logging_collector = on
log_filename = 'postgresql-%Y-%m-%d.log'

# Disable timeouts — this is a single-user research database on a closed network.
# Long-running ETL imports should never be killed by the server.
statement_timeout = 0
idle_in_transaction_session_timeout = 0
lock_timeout = 0
tcp_keepalives_idle = 60
tcp_keepalives_interval = 10
tcp_keepalives_count = 10
EOF
mkdir -p "$PGDATA/logs"
echo "      Done."

# 3. Start PostgreSQL server
echo "[3/5] Starting PostgreSQL server..."
pg_ctl -D "$PGDATA" -l "$PGDATA/logs/startup.log" start
sleep 3   # Give the server a moment to start

# Verify it started
if pg_ctl -D "$PGDATA" status | grep -q "server is running"; then
    echo "      Server is running on port $PGPORT."
else
    echo "ERROR: Server did not start. Check $PGDATA/logs/startup.log"
    exit 1
fi

# 4. Create database and user
echo "[4/5] Creating database and user..."
# Create the application user (no superuser)
psql -p "$PGPORT" -d postgres -c "
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$PGUSER') THEN
            CREATE ROLE $PGUSER LOGIN PASSWORD 'change_me_strong_password';
        END IF;
    END
    \$\$;
"

# Create the database owned by that user
psql -p "$PGPORT" -d postgres -c "
    SELECT 'CREATE DATABASE $PGDB OWNER $PGUSER'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$PGDB')
" -t | psql -p "$PGPORT" -d postgres

# Grant privileges
psql -p "$PGPORT" -d "$PGDB" -c "GRANT ALL PRIVILEGES ON DATABASE $PGDB TO $PGUSER;"
echo "      Done."

# 5. Load schema
echo "[5/5] Loading schema (extensions + tables + views)..."
if [ ! -f "$SCHEMA" ]; then
    echo "ERROR: Schema file not found at $SCHEMA"
    exit 1
fi
psql -p "$PGPORT" -d "$PGDB" -U "$PGUSER" -f "$SCHEMA"
echo "      Done."

# ── Write .env file ───────────────────────────────────────────────────────────
echo ""
echo "Writing .env file..."
cat > "/storage/research/igmp_dp_workspace/garciabaroja_javier/PW_reports/database/pathodb/.env" << EOF
# PathoDB environment — generated by setup_postgres_hpc.sh
POSTGRES_DB=$PGDB
POSTGRES_USER=$PGUSER
POSTGRES_PASSWORD=change_me_strong_password
DATABASE_URL=postgresql://$PGUSER:change_me_strong_password@localhost:$PGPORT/$PGDB
PGPORT=$PGPORT
PGDATA=$PGDATA
EOF
echo "Written to /storage/research/igmp_dp_workspace/garciabaroja_javier/PW_reports/database/pathodb/.env"
echo ""
echo "IMPORTANT: Edit .env and change the password in both"
echo "  POSTGRES_PASSWORD and DATABASE_URL before running the ETL."
echo ""
echo "=== Setup complete ==="
echo ""
echo "Useful commands:"
echo "  Start server : pg_ctl -D $PGDATA start"
echo "  Stop server  : pg_ctl -D $PGDATA stop"
echo "  Connect      : psql -p $PGPORT -d $PGDB -U $PGUSER"
echo "  View logs    : tail -f $PGDATA/logs/postgresql-\$(date +%Y-%m-%d).log"
